/**
 * ภาพ/คลิปประกอบหน้า "นักการตลาด AI" — สร้างด้วย AI (Qwen-Image-2.1 + MiniMax-H3) บนเซิร์ฟเวอร์ Unsloth ของ NAKA-AI
 * เป็นภาพประกอบแนวคิด ไม่ใช่คลิปจริงจาก TikTok/Reels/Shorts และบุคคลในภาพเป็นคนสมมติทั้งหมด
 * ไฟล์นี้สร้างอัตโนมัติจากไฟล์ใน public/marketer-media/ — อย่าแก้ด้วยมือ
 */
const IMAGES = new Set([
  "category-appliances",
  "category-auto",
  "category-beauty",
  "category-electronics",
  "category-fashion",
  "category-food",
  "category-health",
  "category-home",
  "category-kitchen",
  "category-mom_baby",
  "category-other",
  "category-pets",
  "category-sports",
  "category-toys",
  "empty-campaigns",
  "empty-insights",
  "empty-trending",
  "empty-videos",
  "example-bulk-tumbler-car",
  "example-bulk-tumbler-gym",
  "example-bulk-tumbler-office",
  "example-bulk-tumbler-travel",
  "example-recreate-before-after",
  "example-recreate-pov-problem",
  "example-recreate-taste-test",
  "example-recreate-unbox",
  "example-url-airfryer",
  "example-url-earbuds",
  "example-url-serum",
  "example-url-sneaker",
  "expert-facebook",
  "expert-general",
  "expert-lazada",
  "expert-line_oa",
  "expert-shopee",
  "expert-tiktok_shop",
  "hero-1",
  "hero-2",
  "hero-3",
  "influencer-01",
  "influencer-02",
  "influencer-03",
  "influencer-04",
  "influencer-05",
  "influencer-06",
  "influencer-07",
  "influencer-08",
  "influencer-09",
  "influencer-10",
  "showcase-cat-fountain",
  "showcase-coffee-drip",
  "showcase-durian-snack",
  "showcase-herbal-balm",
  "showcase-led-strip",
  "showcase-linen-dress",
  "showcase-lip-tint",
  "showcase-massage-gun",
  "showcase-phone-case",
  "showcase-rice-cooker",
  "showcase-ring-light",
  "showcase-school-bag",
  "showcase-sunscreen",
  "template-campaign_calendar",
  "template-category_opportunity",
  "template-competitor_scan",
  "template-pricing_strategy",
  "template-review_insights",
  "template-roas_analysis",
  "template-search_terms",
  "template-title_optimization",
  "template-trending_products",
  "template-ugc_brief",
  "template-video_script",
  "template-viral_analysis",
  "trend-th-beauty-hair-tonic-drama",
  "trend-th-beauty-setting-spray",
  "trend-th-beauty-toner-pov",
  "trend-th-fashion-live-clearance",
  "trend-th-fashion-sport-shorts",
  "trend-th-food-asmr-fruit",
  "trend-th-food-cereal-shock",
  "trend-th-food-kitkat-drink",
  "trend-th-gadget-mechanic-tools",
  "trend-th-gadget-phone-tripod",
  "trend-th-health-birdnest-drink",
  "trend-th-health-supplement-live",
  "trend-th-home-car-wash-set",
  "trend-th-home-toilet-cleaner",
  "trend-th-other-football-story",
  "trend-th-other-newsjack-flood",
  "trend-th-pet-gummy-frog",
  "trend-th-pet-ling-toy",
  "way-bulk",
  "way-bulk-alt",
  "way-insight",
  "way-insight-alt",
  "way-recreate",
  "way-recreate-alt",
  "way-url",
  "way-url-alt"
])
const VIDEOS = new Set([
  "example-bulk-tumbler-car",
  "example-bulk-tumbler-gym",
  "example-bulk-tumbler-office",
  "example-bulk-tumbler-travel",
  "example-recreate-before-after",
  "example-recreate-pov-problem",
  "example-recreate-taste-test",
  "example-recreate-unbox",
  "example-url-airfryer",
  "example-url-earbuds",
  "example-url-serum",
  "example-url-sneaker",
  "hero-1",
  "hero-2",
  "hero-3",
  "showcase-cat-fountain",
  "showcase-coffee-drip",
  "showcase-durian-snack",
  "showcase-herbal-balm",
  "showcase-led-strip",
  "showcase-linen-dress",
  "showcase-lip-tint",
  "showcase-massage-gun",
  "showcase-phone-case",
  "showcase-rice-cooker",
  "showcase-ring-light",
  "showcase-school-bag",
  "showcase-sunscreen",
  "trend-th-beauty-hair-tonic-drama",
  "trend-th-beauty-setting-spray",
  "trend-th-beauty-toner-pov",
  "trend-th-fashion-live-clearance",
  "trend-th-fashion-sport-shorts",
  "trend-th-food-asmr-fruit",
  "trend-th-food-cereal-shock",
  "trend-th-food-kitkat-drink",
  "trend-th-gadget-mechanic-tools",
  "trend-th-gadget-phone-tripod",
  "trend-th-health-birdnest-drink",
  "trend-th-health-supplement-live",
  "trend-th-home-car-wash-set",
  "trend-th-home-toilet-cleaner",
  "trend-th-other-football-story",
  "trend-th-other-newsjack-flood",
  "trend-th-pet-gummy-frog",
  "trend-th-pet-ling-toy",
  "way-bulk",
  "way-insight",
  "way-recreate",
  "way-url"
])

function path(id, ext) {
  const cut = id.indexOf('-')
  return `/marketer-media/${id.slice(0, cut)}/${id.slice(cut + 1)}.${ext}`
}

/** @returns {string | null} */
export const mkImage = id => (IMAGES.has(id) ? path(id, 'webp') : null)
/** @returns {string | null} */
export const mkVideo = id => (VIDEOS.has(id) ? path(id, 'mp4') : null)
/** @returns {string | null} */
export const mkPoster = id => (VIDEOS.has(id) ? path(id, 'poster.webp') : mkImage(id))
/** id ทั้งหมดในกลุ่ม เช่น mkGroup('showcase') */
export const mkGroup = group => [...IMAGES].filter(id => id.startsWith(`${group}-`))
