/** Optional, original production skills. Installing one creates a normal agent SKILL.md. */
export type SkillCategory = 'story' | 'continuity' | 'cinematography' | 'visual' | 'quality'
export type SkillAgent = 'script_rewriter' | 'extractor' | 'storyboard_breaker' | 'prompt_generator'

export interface LibrarySkill {
  id: string
  agent: SkillAgent
  category: SkillCategory
  title: string
  titleTh: string
  description: string
  descriptionTh: string
  rules: string[]
}

function skill(agent: SkillAgent, category: SkillCategory, parent: string, slug: string,
  title: string, titleTh: string, description: string, descriptionTh: string, ...rules: string[]): LibrarySkill {
  return { id: `${parent}/${slug}`, agent, category, title, titleTh, description, descriptionTh, rules }
}

export const skillLibrary: LibrarySkill[] = [
  skill('script_rewriter', 'story', 'script-rewriter', 'opening-hook', 'Opening hook', 'เปิดเรื่องให้น่าติดตาม',
    'Build a visible question or disruption in the opening seconds.', 'เปิดตอนด้วยเหตุการณ์หรือคำถามที่คนดูอยากติดตาม',
    'Open with a concrete action, discovery, or contradiction already supported by the source.',
    'Show the protagonist reacting before explaining the backstory.',
    'Do not change established facts or delay the first story question with exposition.'),
  skill('script_rewriter', 'story', 'script-rewriter', 'scene-turn', 'Scene turn', 'จุดพลิกของฉาก',
    'Make each scene end in a changed situation.', 'ให้แต่ละฉากจบด้วยสถานการณ์ที่เปลี่ยนไป',
    'Identify what the character wants at the start and what changes by the end.',
    'Use a visible decision, revelation, or consequence as the turn.',
    'Remove repetitive exchanges that leave the situation unchanged.'),
  skill('script_rewriter', 'story', 'script-rewriter', 'conflict-escalation', 'Conflict escalation', 'ไต่ระดับความขัดแย้ง',
    'Raise the cost of pursuing the character goal across scenes.', 'เพิ่มเดิมพันของตัวละครอย่างมีเหตุผลในแต่ละฉาก',
    'Escalate through consequences of prior actions rather than unrelated surprises.',
    'Keep the central relationship and source plot intact.',
    'Let each obstacle force a more specific choice.'),
  skill('script_rewriter', 'story', 'script-rewriter', 'episode-cliffhanger', 'Episode cliffhanger', 'จบตอนแบบค้างใจ',
    'End an episode on a consequential unanswered beat.', 'จบตอนตรงจุดที่มีผลต่อเรื่องและชวนดูต่อ',
    'End on a revelation, decision, or imminent consequence grounded in the episode.',
    'Make the immediate question clear without inventing a new plot thread.',
    'Avoid a generic fade-out after the conflict is fully resolved.'),
  skill('script_rewriter', 'story', 'script-rewriter', 'character-voice', 'Character voice', 'เสียงพูดเฉพาะตัวละคร',
    'Keep each character distinct through dialogue choices.', 'รักษาวิธีพูดที่จำแนกตัวละครแต่ละคนได้',
    'Track each speaker’s formality, sentence length, preferred words, and emotional restraint.',
    'Rewrite dialogue that could be swapped between characters without changing meaning.',
    'Preserve language and relationship conventions established in the source.'),
  skill('script_rewriter', 'story', 'script-rewriter', 'dialogue-subtext', 'Dialogue subtext', 'บทสนทนาที่มีนัย',
    'Let speech carry intent beyond literal words.', 'ทำให้บทพูดมีความหมายแฝงตามแรงจูงใจ',
    'State the scene objective through action and implication instead of repeated explanation.',
    'Use pauses, interruptions, and evasions only where the source supports tension.',
    'Keep spoken lines short enough to perform in the planned scene duration.'),
  skill('script_rewriter', 'continuity', 'script-rewriter', 'story-facts', 'Story facts', 'ข้อเท็จจริงของเรื่อง',
    'Protect established facts while rewriting.', 'รักษาข้อเท็จจริงและความสัมพันธ์เดิมของเรื่อง',
    'Track names, relationships, chronology, secrets, and location rules from the input.',
    'Check every new scene against those facts before saving.',
    'If a fact is unknown, leave it open rather than inventing canon.'),

  skill('extractor', 'continuity', 'extractor', 'character-identity', 'Character identity', 'ตัวตนตัวละคร',
    'Create reusable visual identity notes for recurring characters.', 'บันทึกหน้าตาและลักษณะที่ต้องคงเดิมของตัวละคร',
    'Separate stable traits such as face, build, and hair from changeable wardrobe.',
    'Use only details stated or clearly visible in the script.',
    'Keep names and existing character records consistent across episodes.'),
  skill('extractor', 'continuity', 'extractor', 'wardrobe-bible', 'Wardrobe bible', 'คู่มือเครื่องแต่งกาย',
    'Record costumes as specific visual continuity requirements.', 'กำหนดชุดที่ต้องคงเดิมในแต่ละช่วงเรื่อง',
    'Capture color, fabric, silhouette, accessories, and hair arrangement when specified.',
    'Mark costume changes only when the script indicates a new time, event, or deliberate change.',
    'Do not replace a named uniform or culturally specific outfit with a generic look.'),
  skill('extractor', 'continuity', 'extractor', 'location-identity', 'Location identity', 'เอกลักษณ์สถานที่',
    'Preserve the visual identity of recurring locations.', 'รักษาหน้าตาและตำแหน่งสำคัญของสถานที่',
    'Record layout anchors such as doors, windows, stairs, and dominant furnishings.',
    'Separate permanent architecture from time-of-day lighting.',
    'Reuse an existing scene when location and time match.'),
  skill('extractor', 'continuity', 'extractor', 'hero-props', 'Hero props', 'พร็อพสำคัญ',
    'Identify story-critical props that need repeatable appearance.', 'คัดพร็อพที่มีผลต่อเรื่องและต้องเห็นซ้ำ',
    'Describe material, color, shape, and distinguishing marks without adding story claims.',
    'Keep ordinary set dressing out of the hero-prop list.',
    'Reuse the same prop record when it returns in a later scene.'),
  skill('extractor', 'visual', 'extractor', 'cultural-specificity', 'Cultural specificity', 'รายละเอียดวัฒนธรรม',
    'Preserve setting-specific dress and spaces.', 'รักษารายละเอียดเครื่องแต่งกายและสถานที่ตามบริบทเรื่อง',
    'Use concrete details present in the source for uniforms, interiors, and social setting.',
    'Avoid replacing local details with generic international sets or clothing.',
    'Do not claim cultural details that the source does not establish.'),

  skill('storyboard_breaker', 'cinematography', 'storyboard-breaker', 'dialogue-coverage', 'Dialogue coverage', 'มุมภาพบทสนทนา',
    'Plan readable camera coverage for exchanges.', 'วางภาพคู่สนทนาให้เห็นความสัมพันธ์และปฏิกิริยา',
    'Establish the speakers’ positions before alternating singles or over-shoulder views.',
    'Place each line and reaction in a sub-shot with enough performance time.',
    'Use close-ups for changes in intention, not every line.'),
  skill('storyboard_breaker', 'cinematography', 'storyboard-breaker', 'eyeline-axis', 'Eyeline and axis', 'ทิศสายตาและแกนกล้อง',
    'Keep screen direction understandable across cuts.', 'รักษาทิศทางสายตาและตำแหน่งตัวละครข้ามช็อต',
    'Track who faces whom and which side of the frame each person occupies.',
    'Do not reverse screen direction without an establishing move or motivated crossing.',
    'Describe eyelines when they carry a reveal or reaction.'),
  skill('storyboard_breaker', 'cinematography', 'storyboard-breaker', 'actor-blocking', 'Actor blocking', 'ตำแหน่งและการเคลื่อนของนักแสดง',
    'Define where characters stand and move within the set.', 'กำหนดจุดยืนและทางเดินของตัวละครในฉาก',
    'Anchor entries, exits, and interactions to known doors, furniture, or props.',
    'Keep positions consistent between consecutive sub-shots.',
    'Prefer one motivated movement per sub-shot.'),
  skill('storyboard_breaker', 'cinematography', 'storyboard-breaker', 'motivated-camera', 'Motivated camera', 'การขยับกล้องที่มีเหตุผล',
    'Choose camera movement based on story information.', 'ขยับกล้องเพื่อเน้นข้อมูลหรืออารมณ์ที่เปลี่ยนจริง',
    'Use a locked camera unless movement reveals, follows, or changes emphasis.',
    'State starting position, direction, and ending composition for a moving shot.',
    'Avoid stacking push, pan, orbit, and zoom in one sub-shot.'),
  skill('storyboard_breaker', 'cinematography', 'storyboard-breaker', 'shot-size-rhythm', 'Shot size rhythm', 'จังหวะขนาดภาพ',
    'Vary shot size to support the dramatic beat.', 'เลือกภาพกว้าง กลาง ใกล้ ตามจังหวะเรื่อง',
    'Use a wider frame to establish geography, then tighten when stakes or attention narrow.',
    'Reserve detail inserts for plot-relevant objects or actions.',
    'Avoid repeating identical centered wide shots through an entire exchange.'),
  skill('storyboard_breaker', 'cinematography', 'storyboard-breaker', 'reaction-inserts', 'Reaction inserts', 'ภาพปฏิกิริยา',
    'Show the consequence of important speech or action.', 'ให้เห็นปฏิกิริยาหลังบทพูดหรือการกระทำสำคัญ',
    'Add a reaction only when it changes what the audience understands.',
    'Keep the reacting character and eyeline consistent with the preceding shot.',
    'Do not replace essential action with a decorative close-up.'),
  skill('storyboard_breaker', 'continuity', 'storyboard-breaker', 'edit-continuity', 'Edit continuity', 'ความต่อเนื่องตอนตัดต่อ',
    'Make adjacent shots cut together coherently.', 'ทำให้ภาพต่อกันได้โดยไม่กระโดดตำแหน่งหรือเวลา',
    'Carry hand positions, held props, wardrobe, and screen direction across cuts.',
    'Mark the action point that motivates each cut.',
    'Do not combine incompatible times or locations in one storyboard segment.'),
  skill('storyboard_breaker', 'cinematography', 'storyboard-breaker', 'vertical-framing', 'Vertical framing', 'องค์ประกอบภาพแนวตั้ง',
    'Compose shots for the episode aspect ratio.', 'จัดวางตัวละครให้เหมาะกับสัดส่วนวิดีโอของตอน',
    'Keep faces, hands, and story-critical props visible in a 9:16 frame when that is the project ratio.',
    'Use foreground and background depth instead of empty headroom.',
    'Do not crop a second speaker or reaction out of a required two-person beat.'),
  skill('storyboard_breaker', 'quality', 'storyboard-breaker', 'performable-pacing', 'Performable pacing', 'จังหวะที่นักแสดงเล่นได้',
    'Fit dialogue and action into actual shot duration.', 'ให้บทพูดและการกระทำพอดีกับเวลาของช็อต',
    'Estimate spoken time before finalizing duration.',
    'Split crowded beats into consecutive segments while preserving cause and effect.',
    'Leave a visible pause for a reaction after a major reveal.'),

  skill('prompt_generator', 'visual', 'prompt-generator/character-prompt', 'face-consistency', 'Face consistency', 'ใบหน้าตัวละครคงเดิม',
    'Keep generated portraits recognizably the same character.', 'รักษาใบหน้าตัวละครให้จำได้ทุกภาพ',
    'Describe stable facial proportions, hairline, age range, and distinguishing features consistently.',
    'Separate identity from clothing and pose changes.',
    'Avoid vague beauty adjectives that erase the character’s specific appearance.'),
  skill('prompt_generator', 'continuity', 'prompt-generator/character-prompt', 'costume-reference', 'Costume reference', 'ภาพอ้างอิงเครื่องแต่งกาย',
    'Make costumes easy to reuse in video generation.', 'สร้างภาพชุดที่ใช้ยึดเครื่องแต่งกายในวิดีโอ',
    'Specify exact garment type, color, fabric, silhouette, shoes, and accessories from styling.',
    'Show enough of the full body to verify the outfit.',
    'Do not silently swap a uniform for everyday clothes.'),
  skill('prompt_generator', 'visual', 'prompt-generator/character-prompt', 'expression-range', 'Expression range', 'ช่วงสีหน้า',
    'Create readable expressions without changing identity.', 'สร้างสีหน้าหลากหลายโดยใบหน้ายังเป็นคนเดิม',
    'Describe an observable facial change and body cue for the intended emotion.',
    'Keep facial structure, hair, and costume consistent with the selected reference.',
    'Avoid exaggerated expressions unless the script calls for them.'),
  skill('prompt_generator', 'continuity', 'prompt-generator/scene-prompt', 'set-geography', 'Set geography', 'ผังฉาก',
    'Keep doors, windows, furniture, and travel paths in stable positions.', 'รักษาตำแหน่งประตู หน้าต่าง และเฟอร์นิเจอร์ของฉาก',
    'State the recurring architectural anchors and camera-facing orientation.',
    'Separate permanent set design from temporary action and lighting.',
    'Avoid changing the room category between reference images.'),
  skill('prompt_generator', 'visual', 'prompt-generator/scene-prompt', 'lighting-continuity', 'Lighting continuity', 'แสงต่อเนื่อง',
    'Make the time and source of light consistent across a scene.', 'รักษาทิศและชนิดของแสงให้ตรงกันทั้งฉาก',
    'Specify time of day, key light source, direction, and practical lights.',
    'Keep the same lighting logic in shots from the same scene.',
    'Avoid unexplained changes from warm daylight to clinical fluorescent light.'),
  skill('prompt_generator', 'continuity', 'prompt-generator/video-prompt', 'wardrobe-lock', 'Wardrobe lock', 'ล็อกชุดในวิดีโอ',
    'Keep the exact selected costume visible through the clip.', 'คงเครื่องแต่งกายตามภาพอ้างอิงตลอดคลิป',
    'Use the bound character or look reference for clothing and hair; do not invent a new outfit.',
    'Name a costume change only if the storyboard explicitly depicts one.',
    'Keep wardrobe wording consistent across consecutive shots in the same scene.'),
  skill('prompt_generator', 'cinematography', 'prompt-generator/video-prompt', 'camera-precision', 'Camera precision', 'คำสั่งกล้องชัดเจน',
    'Turn storyboard camera fields into executable video instructions.', 'ระบุมุมและการขยับกล้องให้ตรงสตอรีบอร์ด',
    'State shot size, camera height, angle, subject placement, and one movement for each sub-shot.',
    'Use the storyboard shot type, angle, and movement as constraints.',
    'Do not replace a requested close-up with an unrelated wide establishing shot.'),
  skill('prompt_generator', 'continuity', 'prompt-generator/video-prompt', 'set-lock', 'Set lock', 'ล็อกฉากในวิดีโอ',
    'Keep the selected location stable across generated clips.', 'ใช้สถานที่จากภาพอ้างอิงอย่างต่อเนื่อง',
    'Anchor architecture, dominant objects, and light direction to the bound scene image.',
    'Do not substitute a school, office, or clinical hallway for a mansion or home.',
    'Keep position changes physically possible within the established room.'),
  skill('prompt_generator', 'quality', 'prompt-generator/video-prompt', 'one-action-per-beat', 'One action per beat', 'หนึ่งการกระทำต่อช่วงเวลา',
    'Reduce overloaded video segments.', 'ลดการสั่งหลายเหตุการณ์ในช่วงเวลาสั้นเกินไป',
    'Give each time segment one visible main action and one clear subject.',
    'Move additional actions to later segments in the storyboard order.',
    'Keep dialogue within the time available to perform it.'),
  skill('prompt_generator', 'quality', 'prompt-generator/video-prompt', 'reference-check', 'Reference check', 'ตรวจภาพอ้างอิง',
    'Check that every named visual asset has a usable bound image.', 'ตรวจว่าตัวละคร ฉาก และพร็อพมีภาพอ้างอิงครบ',
    'Reference only characters, locations, and props actually bound to this storyboard.',
    'Use exact asset names so the image-number mapping can resolve them.',
    'If a required image is absent, report the missing asset instead of making up its appearance.'),
  skill('prompt_generator', 'quality', 'prompt-generator/video-prompt', 'shot-review', 'Shot review', 'ตรวจช็อตก่อนสร้าง',
    'Catch prompt contradictions before paid video generation.', 'ตรวจความขัดแย้งก่อนส่งงานสร้างวิดีโอ',
    'Compare the prompt with the storyboard description, camera fields, bound cast, set, and duration.',
    'Flag incompatible wardrobe, location, light, or action before saving the prompt.',
    'Preserve the original story beat when correcting a visual instruction.'),
]

export function renderLibrarySkill(entry: LibrarySkill): string {
  const name = entry.id.split('/').at(-1)
  return `---\nname: ${name}\ndescription: ${entry.description}\n---\n\n# ${entry.title}\n\n${entry.rules.map(rule => `- ${rule}`).join('\n')}\n`
}
