-- NAKA Studio (apps/studio) on PostgreSQL — baseline (docs/adr/0004-shared-postgres-and-queues.md).
-- Generated once from the SQLite schema initSqliteSchema() built (migrations v1–v21 applied).
-- Runs as studio_app with search_path = studio; never name the schema here.
-- Types: INTEGER → bigint (ids are identity columns), Drizzle boolean-mode integers → boolean,
-- REAL → double precision, TEXT → text (timestamps stay ISO-8601 text, JSON stays text).
-- Style presets are seeded at startup (src/core/db/seed.ts), not here: that code also upgrades them.

CREATE TABLE "ai_service_configs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_type" text NOT NULL,
  "provider" text,
  "name" text NOT NULL,
  "base_url" text NOT NULL,
  "api_key" text NOT NULL,
  "model" text,
  "endpoint" text,
  "query_endpoint" text,
  "priority" bigint DEFAULT 0,
  "is_default" boolean DEFAULT false,
  "is_active" boolean DEFAULT true,
  "settings" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "ai_service_providers" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "display_name" text,
  "service_type" text NOT NULL,
  "provider" text NOT NULL,
  "default_url" text,
  "preset_models" text,
  "description" text,
  "is_active" boolean DEFAULT true,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "app_settings" (
  "key" text PRIMARY KEY,
  "value" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "assets" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "drama_id" bigint,
  "episode_id" bigint,
  "storyboard_id" bigint,
  "storyboard_num" bigint,
  "name" text,
  "description" text,
  "type" text,
  "category" text,
  "url" text,
  "thumbnail_url" text,
  "local_path" text,
  "file_size" bigint,
  "mime_type" text,
  "width" bigint,
  "height" bigint,
  "duration" bigint,
  "format" text,
  "image_gen_id" bigint,
  "video_gen_id" bigint,
  "is_favorite" boolean DEFAULT false,
  "view_count" bigint DEFAULT 0,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text
);

CREATE TABLE "campaign_ad_references" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" bigint NOT NULL,
  "title" text NOT NULL DEFAULT '',
  "source_url" text,
  "transcript" text NOT NULL DEFAULT '',
  "notes" text,
  "analysis" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "campaign_creatives" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" bigint NOT NULL,
  "angle" text NOT NULL DEFAULT '',
  "hook" text NOT NULL DEFAULT '',
  "format" text NOT NULL DEFAULT 'ugc',
  "platform" text NOT NULL DEFAULT 'tiktok',
  "duration_sec" bigint NOT NULL DEFAULT 30,
  "cta" text,
  "script" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'draft',
  "episode_id" bigint,
  "episode_number" bigint,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "reference_id" bigint
);

CREATE TABLE "campaign_doc_revisions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doc_id" bigint NOT NULL,
  "version" bigint NOT NULL,
  "content" text NOT NULL DEFAULT '',
  "source" text NOT NULL DEFAULT 'agent',
  "created_at" text NOT NULL
);

CREATE TABLE "campaign_docs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" bigint NOT NULL,
  "kind" text NOT NULL,
  "content" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'draft',
  "version" bigint NOT NULL DEFAULT 1,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  UNIQUE ("campaign_id", "kind")
);

CREATE TABLE "campaign_visuals" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" bigint NOT NULL,
  "kind" text NOT NULL,
  "source_image" text NOT NULL,
  "instruction" text,
  "prompt" text NOT NULL DEFAULT '',
  "task_id" bigint NOT NULL,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "campaigns" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "product_url" text,
  "product_name" text NOT NULL DEFAULT '',
  "product_description" text,
  "product_images" text,
  "brand_notes" text,
  "market" text NOT NULL DEFAULT 'TH',
  "platforms" text,
  "audience" text,
  "goal" text,
  "style" text DEFAULT '3d',
  "aspect_ratio" text DEFAULT '9:16',
  "status" text NOT NULL DEFAULT 'draft',
  "error_msg" text,
  "drama_id" bigint,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text,
  "research_notes" text,
  "budget_thb" double precision,
  "owner_user_id" text NOT NULL DEFAULT 'local'
);

CREATE TABLE "character_looks" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_id" bigint NOT NULL,
  "name" text NOT NULL,
  "notes" text,
  "image_url" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "characters" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "drama_id" bigint NOT NULL,
  "name" text NOT NULL,
  "role" text,
  "description" text,
  "appearance" text,
  "styling" text,
  "final_prompt" text,
  "personality" text,
  "image_url" text,
  "reference_images" text,
  "seed_value" text,
  "sort_order" bigint,
  "local_path" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text
);

CREATE TABLE "clone_projects" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "reference_path" text,
  "reference_transcript" text NOT NULL DEFAULT '',
  "language" text NOT NULL DEFAULT 'th',
  "blueprint_json" text,
  "error_code" text,
  "error_msg" text,
  "render_state" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "render_engine" text NOT NULL DEFAULT 'naka',
  "owner_user_id" text NOT NULL DEFAULT 'local'
);

CREATE TABLE "clone_variants" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint NOT NULL,
  "label" text NOT NULL DEFAULT '',
  "overrides_json" text,
  "status" text NOT NULL DEFAULT 'draft',
  "output_path" text,
  "duration_sec" double precision,
  "error_code" text,
  "error_msg" text,
  "pipeline_task_id" bigint,
  "episode_id" bigint,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "creative_results" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creative_id" bigint NOT NULL,
  "views" bigint,
  "likes" bigint,
  "comments" bigint,
  "shares" bigint,
  "sales_thb" double precision,
  "posted_url" text,
  "posted_at" text,
  "note" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  UNIQUE ("creative_id")
);

CREATE TABLE "dramas" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "description" text,
  "genre" text,
  "style" text DEFAULT '3d',
  "aspect_ratio" text DEFAULT '16:9',
  "total_episodes" bigint DEFAULT 1,
  "total_duration" bigint DEFAULT 0,
  "status" text NOT NULL DEFAULT 'draft',
  "thumbnail" text,
  "tags" text,
  "metadata" text,
  "budget_thb" double precision,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text,
  "owner_user_id" text NOT NULL DEFAULT 'local'
);

CREATE TABLE "episode_characters" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "episode_id" bigint NOT NULL,
  "character_id" bigint NOT NULL,
  "created_at" text NOT NULL
);

CREATE TABLE "episode_props" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "episode_id" bigint NOT NULL,
  "prop_id" bigint NOT NULL,
  "created_at" text NOT NULL
);

CREATE TABLE "episode_scenes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "episode_id" bigint NOT NULL,
  "scene_id" bigint NOT NULL,
  "created_at" text NOT NULL
);

CREATE TABLE "episodes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "drama_id" bigint NOT NULL,
  "episode_number" bigint NOT NULL,
  "title" text NOT NULL,
  "content" text,
  "script_content" text,
  "description" text,
  "duration" bigint DEFAULT 0,
  "status" text DEFAULT 'draft',
  "hook" text,
  "video_url" text,
  "thumbnail" text,
  "image_config_id" bigint,
  "video_config_id" bigint,
  "resolution" text DEFAULT '720p',
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text
);

CREATE TABLE "pipeline_tasks" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" text NOT NULL,
  "key" text NOT NULL,
  "drama_id" bigint,
  "episode_id" bigint,
  "status" text NOT NULL DEFAULT 'running',
  "total" bigint DEFAULT 0,
  "completed" bigint DEFAULT 0,
  "failed" bigint DEFAULT 0,
  "current_key" text,
  "error_msg" text,
  "cancel_requested" bigint DEFAULT 0,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "finished_at" text,
  UNIQUE ("key")
);

CREATE TABLE "props" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "drama_id" bigint NOT NULL,
  "name" text NOT NULL,
  "type" text,
  "description" text,
  "prompt" text,
  "final_prompt" text,
  "image_url" text,
  "reference_images" text,
  "local_path" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text
);

CREATE TABLE "scenes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "drama_id" bigint NOT NULL,
  "episode_id" bigint,
  "location" text NOT NULL,
  "time" text NOT NULL,
  "prompt" text NOT NULL,
  "lighting" text,
  "final_prompt" text,
  "storyboard_count" bigint DEFAULT 1,
  "image_url" text,
  "status" text DEFAULT 'pending',
  "local_path" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text
);

CREATE TABLE "seller_posts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL DEFAULT '',
  "product_name" text NOT NULL DEFAULT '',
  "product_url" text,
  "product_price" text,
  "product_description" text,
  "product_images" text NOT NULL DEFAULT '[]',
  "affiliate_url" text,
  "video_url" text,
  "studio_project_id" bigint,
  "channels" text NOT NULL DEFAULT '[]',
  "language" text NOT NULL DEFAULT 'th',
  "tone" text NOT NULL DEFAULT 'casual',
  "notes" text,
  "content" text NOT NULL DEFAULT '{}',
  "status" text NOT NULL DEFAULT 'draft',
  "error_msg" text,
  "generated_at" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text,
  "video_template_id" text,
  "video_auto" boolean NOT NULL DEFAULT false,
  "video_error" text,
  "owner_user_id" text NOT NULL DEFAULT 'local'
);

CREATE TABLE "storyboard_character_looks" (
  "storyboard_id" bigint NOT NULL,
  "character_id" bigint NOT NULL,
  "look_id" bigint NOT NULL,
  PRIMARY KEY ("storyboard_id", "character_id")
);

CREATE TABLE "storyboard_characters" (
  "storyboard_id" bigint NOT NULL,
  "character_id" bigint NOT NULL,
  PRIMARY KEY ("storyboard_id", "character_id")
);

CREATE TABLE "storyboard_media_selections" (
  "storyboard_id" bigint NOT NULL,
  "slot" text NOT NULL,
  "task_id" bigint NOT NULL,
  "selected_at" text NOT NULL,
  PRIMARY KEY ("storyboard_id", "slot")
);

CREATE TABLE "storyboard_props" (
  "storyboard_id" bigint NOT NULL,
  "prop_id" bigint NOT NULL,
  PRIMARY KEY ("storyboard_id", "prop_id")
);

CREATE TABLE "storyboards" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "episode_id" bigint NOT NULL,
  "scene_id" bigint,
  "storyboard_number" bigint NOT NULL,
  "title" text,
  "location" text,
  "time" text,
  "shot_type" text,
  "angle" text,
  "movement" text,
  "result" text,
  "atmosphere" text,
  "image_prompt" text,
  "video_prompt" text,
  "bgm_prompt" text,
  "sound_effect" text,
  "description" text,
  "duration" bigint DEFAULT 0,
  "composed_image" text,
  "first_frame_image" text,
  "last_frame_image" text,
  "reference_images" text,
  "video_url" text,
  "subtitle_url" text,
  "composed_video_url" text,
  "status" text DEFAULT 'pending',
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text
);

CREATE TABLE "studio_avatars" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "locale" text,
  "image_url" text,
  "image_task_id" bigint,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text,
  "owner_user_id" text NOT NULL DEFAULT 'local'
);

CREATE TABLE "studio_images" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint NOT NULL,
  "kind" text NOT NULL,
  "platform" text,
  "source_image" text NOT NULL,
  "instruction" text,
  "prompt" text NOT NULL DEFAULT '',
  "task_id" bigint NOT NULL,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "studio_influencer_contents" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "influencer_id" bigint NOT NULL,
  "kind" text NOT NULL,
  "product_name" text NOT NULL DEFAULT '',
  "product_image" text,
  "scene" text,
  "instruction" text,
  "language" text,
  "platform" text,
  "duration_sec" bigint,
  "prompt" text NOT NULL DEFAULT '',
  "task_id" bigint,
  "script" text,
  "status" text NOT NULL DEFAULT 'processing',
  "error_msg" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "studio_influencers" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "niche" text,
  "persona" text NOT NULL DEFAULT '',
  "appearance" text NOT NULL DEFAULT '',
  "locale" text,
  "tone" text,
  "image_url" text,
  "image_task_id" bigint,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text,
  "owner_user_id" text NOT NULL DEFAULT 'local'
);

CREATE TABLE "studio_projects" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "product_name" text NOT NULL DEFAULT '',
  "product_url" text,
  "product_description" text,
  "product_images" text,
  "template_id" text NOT NULL,
  "language" text NOT NULL DEFAULT 'th',
  "market" text NOT NULL DEFAULT 'TH',
  "platform" text NOT NULL DEFAULT 'tiktok',
  "aspect_ratio" text NOT NULL DEFAULT '9:16',
  "duration_sec" bigint NOT NULL DEFAULT 24,
  "avatar_id" bigint,
  "tone" text,
  "notes" text,
  "budget_thb" double precision,
  "ai_disclosure" boolean NOT NULL DEFAULT true,
  "status" text NOT NULL DEFAULT 'draft',
  "error_msg" text,
  "drama_id" bigint,
  "episode_id" bigint,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "deleted_at" text,
  "captions" boolean DEFAULT true,
  "caption_style" text DEFAULT 'bold',
  "ai_label_burn_in" boolean DEFAULT false,
  "auto_render" text,
  "source_campaign_id" bigint,
  "influencer_id" bigint,
  "owner_user_id" text NOT NULL DEFAULT 'local'
);

CREATE TABLE "studio_shots" (
  "storyboard_id" bigint NOT NULL,
  "project_id" bigint NOT NULL,
  "role" text NOT NULL DEFAULT '',
  "dialogue" text,
  "on_screen_text" text,
  UNIQUE ("storyboard_id")
);

CREATE TABLE "style_presets" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "value" text NOT NULL,
  "prompt" text NOT NULL,
  "description" text,
  "sort_order" bigint DEFAULT 0,
  "is_active" boolean DEFAULT true,
  "preview_path" text,
  "category" text,
  "source" text NOT NULL DEFAULT 'custom',
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  UNIQUE ("value")
);

CREATE TABLE "sys_task" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" text NOT NULL,
  "storyboard_id" bigint,
  "drama_id" bigint,
  "scene_id" bigint,
  "character_id" bigint,
  "prop_id" bigint,
  "provider" text,
  "config_id" bigint,
  "prompt" text,
  "model" text,
  "params" text,
  "task_id" text,
  "result_url" text,
  "local_path" text,
  "status" text DEFAULT 'processing',
  "error_msg" text,
  "error_code" text,
  "estimated_cost_thb" double precision,
  "source_snapshot" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  "completed_at" text,
  "owner_user_id" text NOT NULL DEFAULT 'local'
);

CREATE TABLE "users" (
  "id" text PRIMARY KEY,
  "display_name" text NOT NULL DEFAULT '',
  "email" text,
  "is_admin" boolean NOT NULL DEFAULT false,
  "last_login_at" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE TABLE "video_merges" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "episode_id" bigint,
  "drama_id" bigint,
  "title" text,
  "provider" text NOT NULL,
  "model" text NOT NULL,
  "status" text DEFAULT 'pending',
  "scenes" text,
  "merged_url" text,
  "duration" bigint,
  "task_id" text,
  "error_msg" text,
  "created_at" text NOT NULL,
  "completed_at" text,
  "deleted_at" text,
  "captioned" boolean DEFAULT false,
  "subtitle_url" text
);



CREATE INDEX idx_campaign_ad_references_campaign ON campaign_ad_references (campaign_id);

CREATE INDEX idx_campaign_creatives_campaign ON campaign_creatives (campaign_id);

CREATE INDEX idx_campaign_doc_revisions_doc ON campaign_doc_revisions (doc_id);

CREATE INDEX idx_campaign_visuals_campaign ON campaign_visuals (campaign_id);

CREATE INDEX idx_campaigns_owner ON campaigns(owner_user_id);

CREATE INDEX idx_character_looks_character ON character_looks (character_id);

CREATE INDEX idx_clone_projects_owner ON clone_projects(owner_user_id);

CREATE INDEX idx_clone_projects_status ON clone_projects (status);

CREATE INDEX idx_clone_variants_project ON clone_variants (project_id);

CREATE INDEX idx_creative_results_creative ON creative_results (creative_id);

CREATE INDEX idx_dramas_owner ON dramas(owner_user_id);

CREATE INDEX idx_episode_characters_character_id ON episode_characters (character_id);

CREATE INDEX idx_episode_characters_episode_id ON episode_characters (episode_id);

CREATE INDEX idx_episode_props_episode_id ON episode_props (episode_id);

CREATE INDEX idx_episode_props_prop_id ON episode_props (prop_id);

CREATE INDEX idx_episode_scenes_episode_id ON episode_scenes (episode_id);

CREATE INDEX idx_episode_scenes_scene_id ON episode_scenes (scene_id);

CREATE INDEX idx_pipeline_tasks_episode_id ON pipeline_tasks (episode_id);

CREATE INDEX idx_seller_posts_owner ON seller_posts(owner_user_id);

CREATE INDEX idx_storyboard_character_looks_look ON storyboard_character_looks (look_id);

CREATE INDEX idx_storyboard_characters_character_id ON storyboard_characters (character_id);

CREATE INDEX idx_storyboard_media_selections_task ON storyboard_media_selections (task_id);

CREATE INDEX idx_storyboard_props_prop_id ON storyboard_props (prop_id);

CREATE INDEX idx_studio_avatars_owner ON studio_avatars(owner_user_id);

CREATE INDEX idx_studio_images_project ON studio_images (project_id);

CREATE INDEX idx_studio_influencer_contents_influencer ON studio_influencer_contents (influencer_id);

CREATE INDEX idx_studio_influencers_owner ON studio_influencers(owner_user_id);

CREATE INDEX idx_studio_projects_drama ON studio_projects (drama_id);

CREATE INDEX idx_studio_projects_owner ON studio_projects(owner_user_id);

CREATE INDEX idx_studio_shots_project ON studio_shots (project_id);

CREATE INDEX idx_sys_task_drama_id ON sys_task (drama_id);

CREATE INDEX idx_sys_task_owner ON sys_task(owner_user_id);

CREATE INDEX idx_sys_task_storyboard_id ON sys_task (storyboard_id);

CREATE INDEX idx_sys_task_type ON sys_task (type);
