-- AI Marketer quick start (prompt box + Thai templates): one-off analyses written by the marketing_insight agent.
-- Per member like every top-level table (owner_user_id, auth/ownership.ts kind 'insight').
-- Ported from naka-drama-studio feat/marketer-topview (SQLite migration v22).

CREATE TABLE IF NOT EXISTS "marketer_insights" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_user_id" text NOT NULL DEFAULT 'local',
  "template_id" text,
  "prompt" text NOT NULL,
  "expert" text NOT NULL DEFAULT 'general',
  "category" text,
  "product_name" text,
  "status" text NOT NULL DEFAULT 'processing',
  "result" text,
  "error_msg" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_marketer_insights_owner ON marketer_insights (owner_user_id, id DESC);
-- startup closes analyses left 'processing' by a restart
CREATE INDEX IF NOT EXISTS idx_marketer_insights_processing ON marketer_insights (status) WHERE status = 'processing';
