-- Social Auto Reply (.scratch/social-auto-reply/spec.md): Social Accounts, their Posts and Comments.
-- All columns now so later tickets do not change the schema. Tokens are plain text, like the stored
-- AI service API keys. Ported from naka-drama-studio feat/social-auto-reply (PR #24, SQLite).
-- An account belongs to one member (owner_user_id, auth/ownership.ts kind 'socialAccount'); posts and
-- comments resolve through their account. One Page has one row: UNIQUE (platform, platform_account_id).

CREATE TABLE IF NOT EXISTS "social_accounts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_user_id" text NOT NULL DEFAULT 'local',
  "platform" text NOT NULL,
  "platform_account_id" text NOT NULL,
  "name" text,
  "avatar_url" text,
  "status" text NOT NULL DEFAULT 'disconnected',
  "access_token" text,
  "refresh_token" text,
  "token_expires_at" text,
  "reply_mode" text NOT NULL DEFAULT 'draft',
  "watching" boolean NOT NULL DEFAULT true,
  "watch_days" bigint NOT NULL DEFAULT 7,
  "reply_to_praise" boolean NOT NULL DEFAULT true,
  "brand_about" text,
  "brand_tone" text,
  "brand_faq" text,
  "brand_forbidden" text,
  "default_language" text NOT NULL DEFAULT 'th',
  "paused_until" text,
  "backoff_step" bigint NOT NULL DEFAULT 0,
  "last_polled_at" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  UNIQUE ("platform", "platform_account_id")
);

CREATE INDEX IF NOT EXISTS idx_social_accounts_owner ON social_accounts (owner_user_id);

CREATE TABLE IF NOT EXISTS "social_posts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" bigint NOT NULL,
  "platform_post_id" text NOT NULL,
  "text" text,
  "url" text,
  "posted_at" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  UNIQUE ("account_id", "platform_post_id")
);

CREATE TABLE IF NOT EXISTS "social_comments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" bigint NOT NULL,
  "post_id" bigint,
  "platform_comment_id" text NOT NULL,
  "parent_platform_comment_id" text,
  "text" text,
  "author_id" text,
  "author_name" text,
  "commented_at" text,
  "status" text NOT NULL DEFAULT 'new',
  "verdict" text,
  "reason" text,
  "fallback" boolean NOT NULL DEFAULT false,
  "judge_attempts" bigint NOT NULL DEFAULT 0,
  "send_attempts" bigint NOT NULL DEFAULT 0,
  "status_note" text,
  "reply_text" text,
  "reply_source" text,
  "reply_platform_id" text,
  "replied_at" text,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL,
  UNIQUE ("account_id", "platform_comment_id")
);

-- the poller and the board read one account's comments by state
CREATE INDEX IF NOT EXISTS idx_social_comments_account_status ON social_comments (account_id, status);
