-- naka-ai (apps/landing) on PostgreSQL — baseline (docs/adr/0004-shared-postgres-and-queues.md).
--
-- One file = the schema D1 had after schema.sql + migrations/0001…0018 (the SQLite files are kept
-- for history only). Runs as account_app with search_path = account; never name the schema here.
--
-- Types: INTEGER → bigint (unix-second timestamps, counters, 0/1 flags), REAL → double precision,
-- TEXT stays text (JSON columns included). AUTOINCREMENT ids → identity columns.

-- ---------------------------------------------------------------------------------------------
-- SQLite compatibility helpers, so the existing SQL keeps its meaning. New code should prefer
-- native PostgreSQL (now(), jsonb operators, strpos).
-- ---------------------------------------------------------------------------------------------

-- datetime('now'[, '+30 seconds', …]) → 'YYYY-MM-DD HH:MM:SS' in UTC, like SQLite. 'now' is the
-- statement's start time (SQLite fixes 'now' per statement too).
CREATE FUNCTION datetime(base text, VARIADIC modifiers text[] DEFAULT '{}') RETURNS text
LANGUAGE plpgsql STABLE AS $$
DECLARE
  t timestamp;
  m text;
BEGIN
  IF base IS NULL THEN RETURN NULL; END IF;
  t := CASE WHEN lower(base) = 'now' THEN statement_timestamp() AT TIME ZONE 'UTC' ELSE base::timestamp END;
  FOREACH m IN ARRAY modifiers LOOP
    IF m IS NULL THEN RETURN NULL; END IF;
    t := t + m::interval;
  END LOOP;
  RETURN to_char(t, 'YYYY-MM-DD HH24:MI:SS');
END $$;

-- unixepoch() → seconds since 1970 (statement time)
CREATE FUNCTION unixepoch() RETURNS bigint
LANGUAGE sql STABLE AS $$ SELECT extract(epoch FROM statement_timestamp())::bigint $$;

-- json_valid(text) → true when the text parses as JSON (used by CHECK constraints)
CREATE FUNCTION json_valid(doc text) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN
  PERFORM doc::jsonb;
  RETURN true;
EXCEPTION WHEN others THEN
  RETURN false;
END $$;

-- json_extract(text, '$.a.b') → the value as text (cast it where a number is needed)
CREATE FUNCTION json_extract(doc text, path text) RETURNS text
LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE WHEN path = '$' THEN doc
              ELSE doc::jsonb #>> string_to_array(substr(path, 3), '.') END
$$;

-- instr(haystack, needle) → 1-based position, 0 when absent
CREATE FUNCTION instr(haystack text, needle text) RETURNS integer
LANGUAGE sql IMMUTABLE AS $$ SELECT strpos(haystack, needle) $$;

-- ---------------------------------------------------------------------------------------------
-- Tables (in dependency order)
-- ---------------------------------------------------------------------------------------------

CREATE TABLE users (
  id text PRIMARY KEY,
  display_name text NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled'))
);

CREATE TABLE plans (
  id text PRIMARY KEY,
  name text NOT NULL,
  monthly_credits bigint NOT NULL DEFAULT 0,
  max_parallel_jobs bigint NOT NULL,     -- queued + running jobs a user may have at once
  price_thb bigint NOT NULL DEFAULT 0,
  on_sale bigint NOT NULL DEFAULT 1 CHECK (on_sale IN (0, 1))
);

CREATE TABLE settings (
  key text PRIMARY KEY,
  value text NOT NULL
);

CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT '',
  price double precision NOT NULL,
  stock bigint NOT NULL DEFAULT 0,
  image_url text NOT NULL DEFAULT '',
  active bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT datetime('now')
);

CREATE TABLE orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_user_id text NOT NULL,
  customer_name text NOT NULL,
  phone text NOT NULL,
  address text NOT NULL,
  items text NOT NULL,            -- JSON: [{product_id, name, price, quantity}]
  total double precision NOT NULL,
  status text NOT NULL DEFAULT 'pending',  -- pending | paid | shipped | cancelled
  note text NOT NULL DEFAULT '',
  created_at text NOT NULL DEFAULT datetime('now')
);

CREATE TABLE conversations (
  line_user_id text PRIMARY KEY,
  display_name text NOT NULL DEFAULT '',
  history text NOT NULL DEFAULT '[]',     -- JSON: [{role, content}]
  human_mode bigint NOT NULL DEFAULT 0,   -- 1 = บอทหยุดตอบ ให้แอดมินคุยเอง
  handoff_reason text NOT NULL DEFAULT '',
  updated_at text NOT NULL DEFAULT datetime('now')
);

CREATE TABLE auth_identities (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider text NOT NULL CHECK (provider IN ('phone', 'google', 'line', 'password')),
  provider_uid text NOT NULL,
  email text,
  verified_at bigint NOT NULL,
  UNIQUE (provider, provider_uid)
);

CREATE TABLE auth_oauth_states (
  id text PRIMARY KEY,
  verifier text NOT NULL,
  expires_at bigint NOT NULL
);

CREATE TABLE auth_otp_requests (
  id text PRIMARY KEY,
  phone text NOT NULL,
  ip_hash text NOT NULL,
  created_at bigint NOT NULL
);

CREATE TABLE auth_password_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('login', 'register')),
  created_at bigint NOT NULL
);

CREATE TABLE auth_password_resets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_key text NOT NULL,
  ip_key text NOT NULL,
  user_id text REFERENCES users(id) ON DELETE CASCADE,
  token_hash text UNIQUE,          -- SHA-256 of the emailed token; the token itself is never stored
  expires_at bigint NOT NULL,
  used_at bigint,
  created_at bigint NOT NULL
);

CREATE TABLE auth_passwords (
  user_id text PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  hash text NOT NULL,
  updated_at bigint NOT NULL
);

CREATE TABLE otp_codes (
  phone text PRIMARY KEY,
  challenge_id text NOT NULL UNIQUE,
  code_hash text NOT NULL,
  expires_at bigint NOT NULL,
  attempts bigint NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
  ready bigint NOT NULL DEFAULT 0 CHECK (ready IN (0, 1)),
  created_at bigint NOT NULL
);

CREATE TABLE sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at bigint NOT NULL,
  created_at bigint NOT NULL
);

CREATE TABLE studio_sso_codes (
  code_hash text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at bigint NOT NULL,
  created_at bigint NOT NULL
);

CREATE TABLE admin_audit (
  rowid bigint GENERATED ALWAYS AS IDENTITY UNIQUE, -- insertion order (SQLite's implicit rowid; the code orders by it)
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  action text NOT NULL CHECK (action IN ('credits', 'package', 'status', 'password')),
  detail text NOT NULL CHECK (json_valid(detail)),
  note text NOT NULL CHECK (length(trim(note)) BETWEEN 1 AND 200),
  created_at bigint NOT NULL,
  actor text NOT NULL DEFAULT ''
);

CREATE TABLE credit_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  delta bigint NOT NULL,
  reason text NOT NULL CHECK (reason IN ('grant', 'purchase', 'job_hold', 'job_refund')),
  job_id text,
  note text NOT NULL DEFAULT '',
  created_at text NOT NULL DEFAULT datetime('now')
);

CREATE TABLE jobs (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  kind text NOT NULL,                     -- e.g. 'image' | 'video' | 'tts' | 'script'
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'done', 'failed')),
  priority bigint NOT NULL DEFAULT 0,     -- higher runs first
  input text NOT NULL DEFAULT '{}',       -- JSON
  output text,                            -- JSON
  cost_credits bigint NOT NULL,
  provider_cost_usd double precision,
  attempts bigint NOT NULL DEFAULT 0,
  max_attempts bigint NOT NULL DEFAULT 3,
  run_after text NOT NULL DEFAULT datetime('now'),
  lease_until text,
  error text,
  created_at text NOT NULL DEFAULT datetime('now'),
  updated_at text NOT NULL DEFAULT datetime('now'),
  finished_at text,
  counts_toward_limit bigint NOT NULL DEFAULT 1 CHECK (counts_toward_limit IN (0, 1))
);

CREATE TABLE subscriptions (
  user_id text PRIMARY KEY,
  plan_id text NOT NULL REFERENCES plans(id),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'cancelled', 'expired')),
  period_end text,
  provider_ref text,
  updated_at text NOT NULL DEFAULT datetime('now'),
  expires_at bigint,
  billing_period text,
  next_credit_at bigint
);

CREATE TABLE payments (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  plan_id text NOT NULL REFERENCES plans(id),
  period text NOT NULL CHECK (period IN ('monthly', 'yearly')),
  amount_satang bigint NOT NULL CHECK (amount_satang > 0),
  method text NOT NULL CHECK (method IN ('promptpay', 'card', 'stripe_checkout')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'successful', 'failed', 'expired')),
  omise_charge_id text UNIQUE,
  stripe_session_id text UNIQUE,
  qr_image_url text,
  expires_at bigint,
  apply_token text,              -- set by the one call that applies the package
  failure text,
  created_at bigint NOT NULL,
  paid_at bigint
);

CREATE TABLE receipts (
  id text PRIMARY KEY,
  payment_id text NOT NULL UNIQUE REFERENCES payments(id),
  user_id text NOT NULL,
  year bigint NOT NULL,
  seq bigint NOT NULL CHECK (seq > 0),
  number text NOT NULL UNIQUE,
  issued_at bigint NOT NULL,
  snapshot text NOT NULL CHECK (json_valid(snapshot)),
  UNIQUE (year, seq)
);

CREATE TABLE ai_videos (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  job_id text UNIQUE,
  kind text NOT NULL CHECK (kind IN ('recreate', 'replace', 'product', 'plan')),
  provider text NOT NULL,
  model text NOT NULL DEFAULT '',
  prompt text NOT NULL CHECK (length(prompt) <= 7000),
  input text NOT NULL CHECK (json_valid(input)), -- media keys, duration, ratio, resolution
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'submitting', 'submitted', 'done', 'failed')),
  provider_task_id text,
  submitted_at bigint,
  output_key text,
  duration_sec double precision,
  error text,
  cost_credits bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

CREATE TABLE marketer_media (
  key text PRIMARY KEY,
  user_id text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('video', 'image', 'output')),
  content_type text NOT NULL,
  size bigint NOT NULL CHECK (size > 0),
  -- A person's photo may only be used once the seller confirms consent (or that the face is AI-made).
  person text CHECK (person IS NULL OR person IN ('consented', 'ai_generated')),
  consent_at bigint,
  created_at bigint NOT NULL
);

CREATE TABLE trending_videos (
  id text PRIMARY KEY,
  source text NOT NULL CHECK (source IN ('curated', 'import', 'api')),
  url text NOT NULL UNIQUE,
  platform text NOT NULL DEFAULT 'tiktok' CHECK (platform IN ('tiktok', 'facebook', 'instagram', 'youtube')),
  region text NOT NULL DEFAULT 'TH' CHECK (length(region) = 2),
  category text NOT NULL DEFAULT 'other',
  title text NOT NULL DEFAULT '' CHECK (length(title) <= 600),
  author text NOT NULL DEFAULT '' CHECK (length(author) <= 120),
  product_name text NOT NULL DEFAULT '' CHECK (length(product_name) <= 200),
  thumbnail_url text CHECK (thumbnail_url IS NULL OR length(thumbnail_url) <= 2000),
  views bigint NOT NULL DEFAULT 0 CHECK (views >= 0),
  likes bigint NOT NULL DEFAULT 0 CHECK (likes >= 0),
  comments bigint NOT NULL DEFAULT 0 CHECK (comments >= 0),
  shares bigint NOT NULL DEFAULT 0 CHECK (shares >= 0),
  revenue_thb bigint CHECK (revenue_thb IS NULL OR revenue_thb >= 0), -- NULL = unknown
  published_at bigint,
  active bigint NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  added_by text NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

CREATE TABLE system_settings (
  key text PRIMARY KEY CHECK (length(key) BETWEEN 1 AND 64),
  value text NOT NULL,
  secret bigint NOT NULL CHECK (secret IN (0, 1)),
  hint text,
  updated_at bigint NOT NULL
);

CREATE TABLE system_audit (
  rowid bigint GENERATED ALWAYS AS IDENTITY UNIQUE, -- insertion order (SQLite's implicit rowid; the code orders by it)
  id text PRIMARY KEY,
  area text NOT NULL CHECK (area IN ('setting', 'plan')),
  target text NOT NULL,
  action text NOT NULL CHECK (action IN ('set', 'clear', 'import', 'create', 'update')),
  detail text NOT NULL CHECK (json_valid(detail)),
  note text NOT NULL DEFAULT '' CHECK (length(note) <= 200),
  actor text NOT NULL DEFAULT '', -- admin Google email, or "โทเคนฉุกเฉิน" for ADMIN_TOKEN
  created_at bigint NOT NULL
);

CREATE TABLE social_accounts (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  platform text NOT NULL CHECK (platform IN ('facebook', 'instagram')),
  external_id text NOT NULL,
  name text NOT NULL,
  token_enc text NOT NULL,
  token_expires_at bigint,
  status text NOT NULL CHECK (status IN ('active', 'revoked', 'error')),
  created_at bigint NOT NULL,
  UNIQUE (user_id, platform, external_id),
  UNIQUE (id, user_id)
);

CREATE TABLE social_media (
  key text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content_type text NOT NULL CHECK (content_type IN ('video/mp4', 'video/webm')),
  size bigint NOT NULL CHECK (size > 0 AND size <= 52428800),
  created_at bigint NOT NULL,
  UNIQUE (key, user_id)
);

CREATE TABLE social_oauth_states (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at bigint NOT NULL
);

CREATE TABLE scheduled_posts (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  social_account_id text NOT NULL,
  media_key text NOT NULL,
  caption text NOT NULL,
  publish_at bigint NOT NULL,
  status text NOT NULL CHECK (status IN ('queued', 'publishing', 'published', 'failed')),
  external_post_id text,
  error text,
  attempts bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  next_attempt_at bigint NOT NULL,
  lease_id text,
  lease_until bigint,
  container_id text,
  phase text NOT NULL DEFAULT 'prepare' CHECK (phase IN ('prepare', 'publish_sent', 'done')),
  polls bigint NOT NULL DEFAULT 0,
  FOREIGN KEY (social_account_id, user_id) REFERENCES social_accounts(id, user_id),
  FOREIGN KEY (media_key, user_id) REFERENCES social_media(key, user_id)
);

CREATE TABLE inbox_settings (
  user_id text PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  mode text NOT NULL DEFAULT 'off' CHECK (mode IN ('off','draft','auto')),
  tone text NOT NULL DEFAULT 'สุภาพ เป็นกันเอง',
  escalate_keywords text NOT NULL DEFAULT '[]',
  updated_at bigint NOT NULL,
  revision bigint NOT NULL DEFAULT 0
);

CREATE TABLE inbox_kb (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title text NOT NULL,
  content text NOT NULL,
  updated_at bigint NOT NULL
);

CREATE TABLE inbox_threads (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  social_account_id text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('comment','dm')),
  external_thread_id text NOT NULL,
  customer_name text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','needs_human','closed')),
  last_message_at bigint NOT NULL,
  last_customer_at bigint NOT NULL DEFAULT 0,
  last_inbound_id text,
  media_id text,
  auto_paused bigint NOT NULL DEFAULT 0 CHECK (auto_paused IN (0,1)),
  revision bigint NOT NULL DEFAULT 0,
  UNIQUE (social_account_id, kind, external_thread_id),
  UNIQUE (id, user_id),
  FOREIGN KEY (social_account_id, user_id) REFERENCES social_accounts(id, user_id)
);

CREATE TABLE inbox_messages (
  id text PRIMARY KEY,
  thread_id text NOT NULL,
  user_id text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('in','out')),
  external_id text UNIQUE,
  body text NOT NULL,
  draft text,
  confidence text CHECK (confidence IN ('high','low')),
  handoff_reason text,
  status text NOT NULL CHECK (status IN ('received','pending','drafted','sent','skipped','failed')),
  approved_by text,
  sent_at bigint,
  created_at bigint NOT NULL,
  message_at bigint NOT NULL,
  reply_target text NOT NULL,
  queue_token text,
  queue_until bigint,
  job_id text,
  draft_lock text,
  draft_until bigint,
  thread_revision bigint,
  settings_revision bigint,
  send_phase text NOT NULL DEFAULT 'ready' CHECK (send_phase IN ('ready','sending','sent','uncertain')),
  send_started_at bigint,
  reply_external_id text,
  error text,
  FOREIGN KEY (thread_id, user_id) REFERENCES inbox_threads(id, user_id) ON DELETE CASCADE
);

CREATE TABLE inbox_webhook_receipts (
  id text PRIMARY KEY,
  body text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done')),
  cursor bigint NOT NULL DEFAULT 0,
  skipped bigint NOT NULL DEFAULT 0,
  error text,
  lease_id text,
  lease_until bigint,
  created_at bigint NOT NULL
);

-- ---------------------------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------------------------
CREATE INDEX idx_admin_audit_user ON admin_audit(user_id, created_at DESC);
CREATE INDEX idx_ai_videos_user ON ai_videos(user_id, created_at DESC);
CREATE INDEX idx_auth_identities_user ON auth_identities(user_id);
CREATE INDEX idx_auth_password_attempts ON auth_password_attempts(key, kind, created_at);
CREATE INDEX idx_auth_password_resets_email ON auth_password_resets(email_key, created_at);
CREATE INDEX idx_auth_password_resets_ip ON auth_password_resets(ip_key, created_at);
CREATE INDEX idx_inbox_kb_user ON inbox_kb(user_id);
CREATE INDEX idx_inbox_messages_pending ON inbox_messages(status, queue_until, created_at);
CREATE INDEX idx_inbox_messages_thread ON inbox_messages(thread_id, created_at, id);
CREATE INDEX idx_inbox_receipts_pending ON inbox_webhook_receipts(status, lease_until, created_at);
CREATE INDEX idx_inbox_threads_user ON inbox_threads(user_id, status, last_message_at);
CREATE INDEX idx_jobs_queue ON jobs(status, priority DESC, run_after);
CREATE INDEX idx_jobs_user ON jobs(user_id, status);
CREATE UNIQUE INDEX idx_ledger_job_reason ON credit_ledger(job_id, reason) WHERE job_id IS NOT NULL;
CREATE INDEX idx_ledger_user ON credit_ledger(user_id);
CREATE INDEX idx_marketer_media_user ON marketer_media(user_id, created_at DESC);
CREATE INDEX idx_oauth_states_expiry ON auth_oauth_states(expires_at);
CREATE INDEX idx_orders_user ON orders(line_user_id);
CREATE INDEX idx_otp_codes_expiry ON otp_codes(expires_at);
CREATE INDEX idx_otp_requests_expiry ON auth_otp_requests(created_at);
CREATE INDEX idx_otp_requests_ip ON auth_otp_requests(ip_hash, created_at);
CREATE INDEX idx_otp_requests_phone ON auth_otp_requests(phone, created_at);
CREATE INDEX idx_payments_user ON payments(user_id, created_at);
CREATE INDEX idx_receipts_user ON receipts(user_id, issued_at DESC);
CREATE INDEX idx_sessions_expiry ON sessions(expires_at);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_social_oauth_expiry ON social_oauth_states(expires_at);
CREATE INDEX idx_social_posts_due ON scheduled_posts(status, next_attempt_at, publish_at);
CREATE INDEX idx_social_posts_lease ON scheduled_posts(status, lease_until);
CREATE INDEX idx_social_posts_user ON scheduled_posts(user_id, created_at);
CREATE INDEX idx_studio_sso_codes_expires ON studio_sso_codes(expires_at);
CREATE INDEX idx_system_audit_created ON system_audit(created_at DESC);
CREATE INDEX idx_trending_list ON trending_videos(active, region, category, views DESC);
CREATE INDEX idx_trending_refresh ON trending_videos(platform, updated_at);

-- ---------------------------------------------------------------------------------------------
-- Seed data (same rows D1 had after all migrations)
-- ---------------------------------------------------------------------------------------------
INSERT INTO plans (id, name, monthly_credits, max_parallel_jobs, price_thb) VALUES
  ('free', 'ฟรี', 0, 1, 0),
  ('starter', 'เริ่มต้น', 30, 1, 399),
  ('pro', 'โปร', 80, 2, 790),
  ('business', 'ธุรกิจ', 160, 4, 1290),
  ('max', 'สูงสุด', 300, 8, 1990);

-- legacy LINE sales agent (src/agent.ts, src/db.ts)
INSERT INTO settings (key, value) VALUES
  ('shop_name', 'ร้านตัวอย่าง naka-ai'),
  ('shop_info', 'จัดส่งทั่วประเทศผ่าน Flash Express ค่าส่ง 40 บาท ส่งฟรีเมื่อซื้อครบ 500 บาท
ชำระเงินผ่าน PromptPay 0XX-XXX-XXXX (ชื่อบัญชี: ...) แล้วส่งสลิปในแชท
ตัดรอบส่งของทุกวัน 14:00 น. เปลี่ยน/คืนสินค้าได้ภายใน 7 วันหากสินค้ามีปัญหา');

INSERT INTO products (id, name, description, category, price, stock) VALUES
  (1, 'เสื้อยืดลายพญานาค สีดำ', 'ผ้าคอตตอน 100% ลายสกรีนทอง ไซส์ S M L XL', 'เสื้อผ้า', 390, 25),
  (2, 'เสื้อยืดลายพญานาค สีขาว', 'ผ้าคอตตอน 100% ลายสกรีนเขียวมรกต ไซส์ S M L XL', 'เสื้อผ้า', 390, 12),
  (3, 'กำไลหินมรกต', 'หินธรรมชาติ ขนาดข้อมือ 16-18 ซม. ปรับได้', 'เครื่องประดับ', 590, 8);
SELECT setval(pg_get_serial_sequence('products', 'id'), 3);
