-- LINE alerts for the back office (src/admin/alerts.ts, page /admin/alerts/). Admins connect their own LINE
-- account by sending a one-time code to the shop's LINE OA; a check every five minutes pushes one message
-- when something needs them. Changes are recorded in system_audit under area 'alert'.
-- Runs as account_app with search_path = account; never name the schema here.

-- Who receives alerts: LINE user ids that sent a valid pairing code to the OA.
CREATE TABLE admin_alert_recipients (
  line_user_id text PRIMARY KEY CHECK (line_user_id ~ '^U[0-9a-f]{32}$'),
  display_name text NOT NULL DEFAULT '',
  added_by text NOT NULL DEFAULT '',   -- the admin who created the code
  created_at bigint NOT NULL
);

-- One-time codes, valid ten minutes. Only the SHA-256 of the code is stored. Every wrong code sent to
-- the OA counts against all open codes; five strikes close them, so the six digits cannot be guessed.
CREATE TABLE admin_alert_pairings (
  code_hash text PRIMARY KEY,
  expires_at bigint NOT NULL,
  attempts bigint NOT NULL DEFAULT 0,
  created_by text NOT NULL DEFAULT '',
  created_at bigint NOT NULL
);

-- Which kinds of alert are sent. Every kind has a row, so the page and the check agree on the defaults.
CREATE TABLE admin_alert_rules (
  key text PRIMARY KEY CHECK (key IN ('jobs_failed', 'studio', 'queue_stuck', 'payment_failed', 'payment_paid')),
  enabled bigint NOT NULL CHECK (enabled IN (0, 1)),
  updated_at bigint NOT NULL
);
INSERT INTO admin_alert_rules (key, enabled, updated_at) VALUES
  ('jobs_failed', 1, 0), ('studio', 1, 0), ('queue_stuck', 1, 0), ('payment_failed', 1, 0), ('payment_paid', 0, 0);

-- What the last check saw, so a problem is announced once (then again after a cool-down) and its recovery once.
CREATE TABLE admin_alert_state (
  key text PRIMARY KEY,
  active bigint NOT NULL DEFAULT 0 CHECK (active IN (0, 1)),
  last_sent_at bigint,
  seen_until bigint                    -- payment_paid: successful payments up to this paid_at were announced
);

-- Messages sent, newest first on the page.
CREATE TABLE admin_alert_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL,
  recipients bigint NOT NULL,
  delivered bigint NOT NULL,
  created_at bigint NOT NULL
);
CREATE INDEX admin_alert_log_created ON admin_alert_log (created_at DESC);

ALTER TABLE system_audit DROP CONSTRAINT system_audit_area_check;
ALTER TABLE system_audit ADD CONSTRAINT system_audit_area_check CHECK (area IN ('setting', 'plan', 'studio', 'price', 'alert'));
ALTER TABLE system_audit DROP CONSTRAINT system_audit_action_check;
ALTER TABLE system_audit ADD CONSTRAINT system_audit_action_check
  CHECK (action IN ('set', 'clear', 'import', 'create', 'update', 'cancel', 'remove', 'test'));
